#!/usr/bin/env ruby

# Author: Benjamin Oakes <hello@benjaminoakes.com>

def show_usage
  STDERR.puts <<EOF
Usage: #{$PROGRAM_NAME} [ --help ]

Checks a volume's free space.  Meant for a cron job.

  --help      Show this help text.
EOF
  exit(-1)
end

if ARGV.any? { |a| '--help' == a }
  show_usage
end

VOLUME_NAME = 'Time Machine'
VOLUME_PATH = "/Volumes/#{VOLUME_NAME}"

free_space_table = %x(df)
free_space_table.each do |line|
  match_data = line.match(/(\d+)%\s+#{VOLUME_PATH}$/)
  unless match_data.nil?
    percentage = match_data[1].to_i
    if percentage >= 98
      STDERR.puts "#{VOLUME_PATH} is getting full (#{percentage}%)"
    end
  end
end

