#!/usr/bin/env bash
# Author: Benjamin Oakes <hello@benjaminoakes.com>

function show_usage {
	cat <<EOF
Usage: $0 cutoff

Check whether free disk space (df) is above a cutoff percentage.

Example:

	$0 80
EOF
	exit -1
}

if [ $# -ne 1 ]; then
	show_usage
fi

# Facility was chosen arbitrarily; has to be between "local0" and "local7" on Ubuntu
facility="local0"
prefix="[$(basename "$0")]"
cutoff="$1"
percent="$(df / | grep -o '[0-9]\+%' | sed 's/%//')"
postfix="$cutoff% cutoff"

if [ $percent -gt $cutoff ]; then
	msg="$prefix Above $postfix"
	logger -p "$facility.warning" "$msg"
	echo $msg
else
	logger -p "$facility.notice" "$prefix Below $postfix"
fi
