#!/usr/bin/env ruby
# Author: Benjamin Oakes <hello@benjaminoakes.com>

require 'csv'

def show_usage
  STDERR.puts <<EOF
Usage: #{$PROGRAM_NAME} [ --help ] filename

Turn a CSV file into an HTML table.

  --help        Show this help text.
  filename      Input filename.
EOF
  exit(-1)
end

if ARGV.any? { |a| '--help' == a }
  show_usage
end

puts '<table>'

is_first_line = true

CSV::Reader.parse(ARGF.readlines.join) do |row|
  puts '<tr>'

  if is_first_line
    row.each do |value|
      puts "<th>#{value}</th>"
    end
  else
    escaped_values = row.map { |value| value.nil? ? 'NULL' : value.gsub("'", "\\'") }

    escaped_values.each do |escaped_value|
      puts "<td>#{escaped_value}</td>"
    end
  end

  puts '</tr>'

  is_first_line = false
end

puts '</table>'
puts

