#!/usr/bin/env bash

# Print out the current date.  Nice for making backups.
# 
# Example:
# 
#     cp filename.txt filename.$(datestamp).txt
# 
# Author: Benjamin Oakes <hello@benjaminoakes.com>

date +date_%Y-%m-%d

