#!/usr/bin/env ruby

# Author: Benjamin Oakes <hello@benjaminoakes.com>

require 'erb'

def show_usage
  STDERR.puts <<EOF
Usage: #{$PROGRAM_NAME} [--help] filename

Run a file through ERB and spit out the result.

  --help      Show this help text.
  filename    Input file.
EOF
  exit(-1)
end

if ARGV.any? { |a| '--help' == a }
  show_usage
end

template = ARGF.readlines
template_shell = ERB.new(template, 0, '%<>')
puts template_shell.result

