#!/usr/bin/env bash

# Rather than copying and pasting what GitHub throws at you (and crossing your fingers), do this.
# 
# Author: Benjamin Oakes <hello@benjaminoakes.com>

if [ "$1" == "--help" ] || [ "$1" == "" ]; then
  cat <<EOF
Usage: $0 [--help] repository_name

Scripts the process of setting up a GitHub repository locally.

  --help              Show this help text.
  repository_name     Name of the repository
EOF
  exit -1
fi

GITHUB_USERNAME='benjaminoakes'
REPOSITORY_NAME="$1"

echo Creating github repository $REPOSITORY_NAME

mkdir "$REPOSITORY_NAME"
cd "$REPOSITORY_NAME"
git init
touch README
git add README
git commit -m 'first commit'
git remote add origin "git@github.com:$GITHUB_USERNAME/$REPOSITORY_NAME.git"
git push origin master

