#!/usr/bin/env ruby

# Markdown to HTML converter.  (I'm pretty sure there's something like this included in BlueCloth now, though...)
# 
# Author: Benjamin Oakes <hello@benjaminoakes.com>

require 'rubygems'
require 'bluecloth' # Needed to be installed on OS X 10.5

def show_usage
  STDERR.puts <<EOF
Usage: #{$PROGRAM_NAME} [--help] filename

Run a file through Markdown (BlueCloth) and spit out the corresponding HTML.

  --help      Show this help text.
  filename    Input file.
EOF
  exit(-1)
end

if ARGV.any? { |a| '--help' == a }
  show_usage
end

puts BlueCloth.new(ARGF.readlines).to_html

