#!/usr/bin/env bash

# Author: Benjamin Oakes <hello@benjaminoakes.com>

if [ "$1" == "--help" ] || [ "$1" = "" -o "$2" != "" ]; then
  cat <<EOF
Usage: $0 [--help] term

What man is to C and ri is to Ruby, $0 is to Matlab.

  --help      Show this help text.
  term        The term to look up.
EOF
  exit -1
fi

# CLI
echo "disp('--- Begin STDOUT ---'); help $1; disp('--- End STDOUT ---');" \
  | $HOME/bin/matlab/bin/matlab -nosplash -nodesktop \
  | ruby -e "
      within = false
  
      ARGF.each_line do |line|
        if line.match(/--- Begin STDOUT ---/)
          within = true
        elsif line.match(/--- End STDOUT ---/)
          within = false
        else
          puts line if within
        end
      end
    "

# # TODO GUI
# echo "doc $1" \
#   | matlab -nosplash -nodesktop

