#!/usr/bin/env ruby
# Author: Benjamin Oakes <hello@benjaminoakes.com>

def show_usage
  STDERR.puts <<EOF
Usage: #{$PROGRAM_NAME} [--help] filename

Print all unique lines (from a file or STDIN) to STDOUT (i.e., remove duplicate lines).

It's like uniq, but uniq only works on adjacent lines.  The first occurrence gets preference.

  --help        Show this help text.
  filename      Input filename
EOF
  exit(-1)
end

if ARGV.any? { |a| '--help' == a }
  show_usage
end

puts ARGF.readlines.uniq

