#!/usr/bin/env ruby

# Author: Benjamin Oakes <hello@benjaminoakes.com>

def show_usage
  STDERR.puts <<EOF
Usage: #{$PROGRAM_NAME} [--help] filename

Reverse the lines of a plain text file.

  --help      Show this help text.
  filename    Input file.
EOF
  exit(-1)
end

if ARGV.any? { |a| '--help' == a }
  show_usage
end

puts ARGF.readlines.reverse

