#!/usr/bin/env ruby

# Delete occurrences of the given pattern from STDIN.  Useful for canned regexes (over say, s/pattern/d in vim).
# 
# Author: Benjamin Oakes <hello@benjaminoakes.com>

if ARGV.length != 1
  puts "Usage: #{$PROGRAM_NAME} pattern | --erb | --sh-comment"
  exit(-1)
end

pattern = case ARGV[0]
# FIXME
# when '--blank'
#   /^$/
when '--erb'
  /<%.*?%>/m
when '--sh-comment' # For Ruby, Perl, Bash, etc.
  /#.*$/
else
  Regexp.new(ARGV[0])
end

text = STDIN.readlines.join
puts text.gsub(pattern, '')

