#!/usr/bin/env ruby
# Author: Benjamin Oakes <hello@benjaminoakes.com>

def show_usage
  STDERR.puts <<EOF
Usage: #{$PROGRAM_NAME} [--help] string1 string2 ... stringN

Print lengths of strings.

  --help      Show this help text.
EOF
  exit(-1)
end

if ARGV.empty? || ARGV.any? { |a| '--help' == a }
  show_usage
else
  ARGV.each do |string|
    puts "#{string.length} #{string}"
  end
end

