#!/usr/bin/env ruby

# Author: Benjamin Oakes <hello@benjaminoakes.com>

require 'rubygems'
require 'redcloth'

def show_usage
  STDERR.puts <<EOF
Usage: #{$PROGRAM_NAME} [--help] filename

Run a file through Textile (RedCloth) and spit out the corresponding HTML.

  --help      Show this help text.
  filename    Input file.
EOF
  exit(-1)
end

if ARGV.any? { |a| '--help' == a }
  show_usage
end

puts RedCloth.new(ARGF.readlines.join).to_html

