#!/usr/bin/env ruby

# Author: Benjamin Oakes <hello@benjaminoakes.com>

class String
  def truncate(cutoff = 30, replacement_string = '...')
    if self.length <= cutoff
      return self
    else
      return self[0, [0, cutoff - replacement_string.length].max] + replacement_string
    end
  end
end

def show_usage
  STDERR.puts <<EOF
Usage: #{$PROGRAM_NAME} [ --help | length ]"

Truncate a string given via STDIN.

  --help      Show this help text.
  length      Length of truncated text.
EOF
  exit(-1)
end

if ARGV.length != 1 || ARGV.any? { |a| '--help' == a }
  show_usage
end

length = ARGV[0].to_i
text = STDIN.readlines.join

puts text.truncate(length)

